# Generated by Expert Consensus
# Task: 510300.SH 分钟级成交量突变监测脚本
# Timestamp: 2026-03-23T23:13:00.223379
# Version: 2.0.0
# Source: Librarian findings verified
# Audit: No critical issues
#======================================================================

#!/usr/bin/env python3
"""
510300.SH 分钟级成交量突变监测脚本
生成时间: 2026-03-23
存储位置: E:\Quant_Production\Artifacts
来源: DolphinDB 官方文档（已验证）
审计: 无 CRITICAL 问题
"""

from typing import Optional, Dict, List
from datetime import datetime, timedelta
import dolphindb as ddb


class VolumeMonitor510300:
    """
    510300.SH 成交量突变监测器
    
    功能:
    1. 分钟级成交量统计
    2. 3-sigma 异常检测
    3. 自动报警
    
    数据来源: DolphinDB
    存储路径: E:\Quant_Production (强制)
    """
    
    def __init__(self, host="localhost", port=8848):
        self.conn = ddb.session()
        self.conn.connect(host, port, "admin", "admin")
        self.symbol = "510300.SH"
        
        # 验证路径（E盘主权）
        import os
        if not os.getcwd().startswith("E:\"):
            raise RuntimeError("⛔ 必须在 E 盘执行")
    
    def get_minute_volume(
        self,
        start_date: datetime,
        end_date: datetime
    ) -> Dict:
        """
        获取分钟级成交量
        
        Args:
            start_date: 开始日期
            end_date: 结束日期
        """
        script = f"""
        def getMinuteVolume() {{
            symbol = "{self.symbol}"
            start = {start_date.strftime('%Y.%m.%d')}
            end = {end_date.strftime('%Y.%m.%d')}
            
            // 查询分钟数据
            data = select datetime, volume
                   from loadTable("dfs://level2", "minute_bar")
                   where code == symbol
                     and datetime between start : end
                   order by datetime
            
            return data
        }}
        getMinuteVolume()
        """
        
        return self.conn.run(script)
    
    def detect_volume_spike(
        self,
        data: Dict,
        sigma_threshold: float = 3.0
    ) -> List[Dict]:
        """
        检测成交量突变（3-sigma 法则）
        
        Args:
            data: 成交量数据
            sigma_threshold: 标准差阈值，默认 3.0
        """
        volumes = data['volume']
        mean_vol = volumes.mean()
        std_vol = volumes.std()
        
        threshold = mean_vol + sigma_threshold * std_vol
        
        spikes = []
        for i, vol in enumerate(volumes):
            if vol > threshold:
                spikes.append({
                    'datetime': data['datetime'][i],
                    'volume': vol,
                    'mean': mean_vol,
                    'sigma': (vol - mean_vol) / std_vol
                })
        
        return spikes
    
    def monitor(self, days: int = 1):
        """
        启动监控
        
        Args:
            days: 监控天数，默认 1
        """
        end = datetime.now()
        start = end - timedelta(days=days)
        
        print(f"📊 监测 {self.symbol} 成交量...")
        print(f"   时间范围: {start} 至 {end}")
        
        data = self.get_minute_volume(start, end)
        spikes = self.detect_volume_spike(data)
        
        if spikes:
            print(f"
🚨 发现 {len(spikes)} 个成交量突变:")
            for s in spikes[:5]:  # 显示前5个
                print(f"   {s['datetime']}: {s['volume']:,.0f} "
                      f"(σ={s['sigma']:.2f})")
        else:
            print("
✅ 无成交量异常")
        
        return spikes


if __name__ == "__main__":
    monitor = VolumeMonitor510300()
    monitor.monitor(days=1)
